---
title: "p8105_hw1_sl5454"
output: html_document
date: "2024-09-12"
---

```{r}
library(tidyverse)
```

##Problem 1

```{r problem_1}
data("penguins", package = "palmerpenguins")

num_row = nrow(penguins)
num_col = ncol(penguins)
mean_flipper_length = mean(penguins$flipper_length_mm, na.rm = TRUE)
summary(penguins)

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point() +
  labs(title = "Flipper Length vs Bill Length",
       x = "Bill Length (mm)",
       y = "Flipper Length (mm)")

ggsave("flipper_vs_bill_scatterplot.pdf")
```
The penguins data set contains observations of three species of penguins collected from three islands.The data set includes sex, years, and various physical measurements of the 
penguins, such as flipper length, which has an average value of 200.9152.The dataset consists of 344 #rows and 8 columns, but some measurements contain missing data.

##Problem 2

```{r}
p2_df =
  tibble(
    sample = rnorm(n = 10),
    log_samp = sample > 0,
    char_vector = sample(letters, 10, replace = TRUE),
    f_vector = factor(sample(c("level1", "level2", "level3"), 10, replace = TRUE))
  )
```


